### ISSUE TITLE
Selecting more glyphs than needed

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#127]
When selecting glyphs from the glyph table, sometimes glyphs from training glyphs get selected as well (and vice versa).

**Comment by nminnie** [comment]
fixed daaf207fde36e8b73c4013ed26520af7dcff5375

**Comment by vigliensoni** [comment]
Since a user can be working in adding more glyphs from a page to the
classifier, isn't this the expected behaviour?

**Comment by nminnie** [comment]
@vigliensoni 
I see what you mean but this is different. It's a bug where when selecting page glyphs, classifier glyphs hidden underneath get selected as well, even though they do not match the selected page glyphs.
