### ISSUE TITLE
Center preview image to highlighted connected component

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#139]
When the user chooses a connected component in the glyphs pane, the highlighted connected component in the page pane should be as much centered as possible on this page. In the current behaviour, the highlighted glyph sometimes appears right next to the border of the pane.

![screen shot 2018-02-12 at 12 25 55 pm](https://user-images.githubusercontent.com/492229/36110239-ecbd3ba4-0fef-11e8-82cc-f767e4b03e1c.png)

**Comment by nminnie** [comment]
967629acc60cf4c4e62a87ee5a7f7881f7e16f37
