### ISSUE TITLE
Glyphs in Page pane should fit in the width of that pane

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#141]
Glyphs of the current page should fit in the Page pane's width. 

In the current behavior, the user has to scroll in the Page pane to see all glyphs:

![screen shot 2018-02-14 at 12 51 00 pm 2](https://user-images.githubusercontent.com/492229/36219613-f8e654b4-1185-11e8-8d2e-3244b19281a6.png)

**Comment by deepio** [comment]
@nminnie Can you attach a commit to this please?

**Comment by nminnie** [comment]
@deepio I don't know which commit it is, but I don't see it happening anymore, even with really big manuscripts. 
And in the CSS file, the div for that panel does not allow "overflow-x: scroll", only "overflow-y: scroll"
