### ISSUE TITLE
IC Summer 2018 overview

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#143]
- [x] Triage, prioritize, and fix issues
- [x] Convert Inga Behrendt and Andrea Klassen's suggestions into issues
- [x] Implement renaming and deleting classes and subclasses
- [x] Implement exporting and importing classes and subclasses
- [ ] Create XML or JSON mapping between IC Gamera XML output (+ Pitch) and MEI encoding  
- [x] Provide ability to view color images in preview image
- [x] Develop IC optimizer RODAN job
- [ ] Implement Gamera's Biollante optimization as RODAN job
- [ ] Test IC performance at large scale

**Comment by nminnie** [comment]
**Note:** Optimizations were implemented within IC, not as a separate job.

**Comment by dchiller** [comment]
Creating separate issues for remaining tasks (see DDMAL/Rodan#891  and DDMAL/Rodan#892).
