### ISSUE TITLE
Install Gamera on Mac OS X Version 10.11 and 10.12

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#16]
Gamera currently does not work on newer operating systems. When attempting to install Gamera, the error received is:
error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/gamera': Operation not permitted

**Comment by pf-physics** [comment]
Was able to finish installation by attaching --user to the installation

**Comment by ahankinson** [comment]
You can also use the homebrew version of python 2.7. That way you don't need to use `sudo` for any installations.

**Comment by vigliensoni** [comment]
@pf-physics, is the installation of Gamera for this set up documented
somewhere?

**Comment by pf-physics** [comment]
I just added the instructions into the DDMAL Gamera readme file
