### ISSUE TITLE
Zooming makes highlighted glyphs disappear

### ISSUE THREAD

**Issue by nminnie** [DDMAL/Interactive-Classifier#161]
Clicking on either of the zooming slide bars (in the preview image or in the page glyphs) makes highlighted glyphs disappear.
These glyphs re-appear when the user clicks on another glyph or selects other glyphs.

**Comment by vigliensoni** [comment]
This is linked to #129 

@nminnie Try to do a triaging of issues in order to avoid duplication.

**Comment by nminnie** [comment]
@vigliensoni 
These 2 issues are caused by different things, although they both make the glyphs disappear. 
#129 is because the glyphs are too small. 
#161 is because glyphs are highlighted.

**Comment by vigliensoni** [comment]
🎯
