### ISSUE TITLE
Change zooming icons

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#172]
The order of the magnifying icons is usually the opposite of what we currently have: zoom out in the left, zoom in in the right.

Also, the icons look pretty pixelated. Are you using vector-based icons? 

![screen shot 2018-07-24 at 1 11 33 pm](https://user-images.githubusercontent.com/492229/43154659-1c7db10c-8f43-11e8-81ee-32dc9fd98373.png)

**Comment by nminnie** [comment]
@vigliensoni 
I've swapped the positions of the zoom buttons.
I'm using bootstrap glyphicons, which actually have high resolution when I make them really big. 
I changed the CSS a bit to make the icons more clear.

**Comment by nminnie** [comment]
Done! 7bac0ae5a4c96babece5cc60c303a493ebfbe15c
