### ISSUE TITLE
Page glyphs pane should fill browser space when not using Classifier pane

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#173]
When pressing "Classifier glyphs" to not display the glyphs in the classifier, the free space in the browser left by this pane should be filled by the page glyphs. 

Also, the "Classifier glyphs" tab should be highlighted if the pane is active.

This functionality was working before. 

![screen shot 2018-07-24 at 1 16 01 pm](https://user-images.githubusercontent.com/492229/43154887-d734fa82-8f43-11e8-8eac-ad22b1966edc.png)

**Comment by nminnie** [comment]
Fixed 9f57c30a1c78bed1ec3463da027a922938ad6b08
