### ISSUE TITLE
Decouple Rodan job from IC logic

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#176]
The IC logic and the Rodan job declaration are currently coupled. We should decouple them.

See https://github.com/DDMAL/Rodan/wiki/Write-a-Rodan-job-package

**Comment by nminnie** [comment]
@vigliensoni 
Am I correct in understanding that this repo is essentially the IC wrapper, and we want to extract the IC logic from it so that it can run outside of Rodan as a standalone software?
Please correct me if I'm wrong.

**Comment by vigliensoni** [comment]
@nminnie No, this repo contains the code and the wrapper. Just separate the wrapper and the IC logic  into different files.

**Comment by nminnie** [comment]
ace9a9163dd527045ad225dda5eba44d51fadc29
