### ISSUE TITLE
Collapse buttons for page glyphs and preview image

### ISSUE THREAD

**Issue by nminnie** [DDMAL/Interactive-Classifier#183]
Currently there is a collapse button (at the top) only for classifier glyphs. We should also have collapse buttons for the page glyphs pane and preview image.

**Comment by vigliensoni** [comment]
As discussed, these buttons should allow the user to visualize, or to not
visualize, the corresponding panes: "classifier glyphs", "page glyphs", and
"preview image"

**Comment by nminnie** [comment]
Implemented c02b669c3ac4247845699f0764f182f1125a9c9a
