### ISSUE TITLE
Select multiple glyphs with shift

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#19]
Currently, the user is able to select multiple glyphs by clicking and dragging the cursor around them. Being able to select multiple glyphs with shift and arrow keys would allow the user to classify glyphs more easily.

**Comment by deepio** [comment]
It is present in the master branch, but not in the dev.

**Comment by deepio** [comment]
It's finished on the Compute Canada server, but not on the dev.

**Comment by pf-physics** [comment]
This was already implemented on the develop branch
