### ISSUE TITLE
Adding Authenticator.js

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#20]
Clicking on the confirm button after clicking the "Submit Corrections and Re-Classify" as well as "Finalize Classification and Save GameraXML" doesn't seem to do anything.

It's possible that the button works but we are setting up the Rodan workflow improperly. We are still investigating.

**Comment by pf-physics** [comment]
We found that the error we get when we click submit is:
"Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)"
as well as:
"POST https://api.dev.rodan.simssa.ca/interactive/ab2ce2ed-f44a-4be0-aeaa-0091660cfd0f/ca165d16-a0db-448d-a659-34a4cb083e82/ 401 (UNAUTHORIZED)"

We are wondering if the confirm button works, but we do not have the proper authorization to confirm the changes.

**Comment by vigliensoni** [comment]
I will double check the permissions for your accounts

On Tue, May 9, 2017 at 1:08 PM, Sacha Perry-Fagant <notifications@github.com

**Comment by pf-physics** [comment]
There is an issue around authenticator.js We discovered that the problem is that we are getting timed out so the timed authentication must not be working.
(If you submit a change really quickly then it works, otherwise it doesn't)

**Comment by pf-physics** [comment]
We found that the authenticator.js file is not used by the rodan dev. When we tried to use the authenticator, the interactive classifier on rodan didn't work. We need to debug the authenticator.

**Comment by pf-physics** [comment]
This is an old issue. We've created more relevant issues since then.
