### ISSUE TITLE
progress not saving in Rodan

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Interactive-Classifier#223]
When we were classifying neumes in the Interactive Classifier in Rodan, saved it and closed the tab, it was not saved in Rodan, as when we re-opened it in "Run Jobs" in Rodan, it reverted back to the original one, rather than the one we just corrected. This also happens to Neon in Rodan, as described in issue #664 in Neon (https://github.com/DDMAL/Neon/issues/664).

**Comment by GabbyHalpin** [comment]
@carrieeex For the save function, does this happen all the time, or just sometimes?  Does it still happen after you click the save button? what exactly happens? It will help us pinpoint where the issue is happening

**Comment by carrieeex** [comment]
> @carrieeex For the save function, does this happen all the time, or just sometimes? 

Yes, all the time.
> Does it still happen after you click the save button? what exactly happens? It will help us pinpoint where the issue is happening

So if we classify something in IC, after clicking the save button, and close the window, and we re-open it in Rodan, it would be the same as we open it in the first place; the progress was not saved.

**Comment by GabbyHalpin** [comment]
@carrieeex Alright, we will look into it more. Weirdly enough when I run Rodan locally, save, exit the tab and then come back, the progress is still there. it is possible that this issue was fixed previously but not pushed to master, which is what you guys are working from.

**Comment by carrieeex** [comment]
> @carrieeex Alright, we will look into it more. Weirdly enough when I run Rodan locally, save, exit the tab and then come back, the progress is still there. it is possible that this issue was fixed previously but not pushed to master, which is what you guys are working from.

Thanks for checking this! and I just ran IC in Rodan2 and it actually saved my progress! Sorry. I should check it earlier. Can my fellow testers help me to confirm this (the IC is saving the progress)? @thesoundbyle @JoyfulGen @yinan Thank you! If this is not a problem anymore we can close this issue.

**Comment by carrieeex** [comment]
The progress now can be saved in Rodan, thanks for looking into this issue @GabbyHalpin !
