### ISSUE TITLE
The resize window functionality does not render or takes too long 

### ISSUE THREAD

**Issue by deepio** [DDMAL/Interactive-Classifier#25]
Ability to resize window panels within the app.

**Comment by pf-physics** [comment]
Changed resize frames to accommodate a new region (commit c8bf2d7)

**Comment by pf-physics** [comment]
Currently resize windows depends on the coordinates of the mouse which makes resizing a little buggy.

**Comment by nminnie** [comment]
Resizing window requires mousemove and takes time, or does not render properly. 
The code is in RodanDashboardView.js
![screen shot 2018-07-24 at 10 59 34 am](https://user-images.githubusercontent.com/26179067/43147394-f20b5c92-8f30-11e8-9c4f-fad4373e9cf4.png)

**Comment by nminnie** [comment]
Fixed 676628efc05e6496a9e3351d6c9231984eda5838
