### ISSUE TITLE
Connect the Rodan Client to Rodan

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#28]
I am trying to run the Rodan server so that the Rodan Client can work with it.
I am currently getting the error:
XMLHttpRequest cannot load http://127.0.0.1:8000/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://132.206.14.114:9002' is therefore not allowed access.

**Comment by musicus** [comment]
👍
