### ISSUE TITLE
Find the Token

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#36]
Find where the user token is stored in Rodan in order to pass it to the interactive classifier

**Comment by ahankinson** [comment]
https://github.com/DDMAL/Rodan/blob/master/rodan/views/auth.py#L49-L56

**Comment by pf-physics** [comment]
So in order to get the token, we need to user information as well. So the issue is now "Find the username and password".

**Comment by ahankinson** [comment]
Not really. You need to find the user object. It will have a token field on it, with the value of the token.

**Comment by ahankinson** [comment]
Have you tried printing `request.user.username` to the template page somewhere to see if that works? If it does, then you should just be able to do `request.user.token` in the template.

**Comment by pf-physics** [comment]
I just get an empty string in both these cases.

**Comment by ahankinson** [comment]
and just `request`?

**Comment by pf-physics** [comment]
Also an empty string

**Comment by pf-physics** [comment]
Duplicate issue #34
