### ISSUE TITLE
Edit Rodan Job so that it Has 3 Inputs

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#52]
The Rodan interactive classifier job should have three inputs. The new input should allow the interactive classifier to use previously classified glyphs in order to do an initial classification.
Right now the only way to do this in a workflow is to add an extra Gamera automatic classifier.

**Comment by vigliensoni** [comment]
What are the three inputs for?

On Wed, Jun 7, 2017 at 3:08 PM, Sacha Perry-Fagant <notifications@github.com
