### ISSUE TITLE
Celery Error: Rodan Interactive Classifier Job with 3 Inputs

### ISSUE THREAD

**Issue by pf-physics** [DDMAL/Interactive-Classifier#53]
When the interactive classifier has 3 inputs, after doing one classification, celery gives the error:
Task Interactive Classifier raised unexpected TypeError('knn id_name not a list or list is empty',)

**Comment by vigliensoni** [comment]
@pf-physics  please do close issues from the actual commit you used to fix it, and/or provide an explanation about how you fixed the issue.
