### ISSUE TITLE
Create classifier glyphs view

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/Interactive-Classifier#69]
The user should be able to see and interact with a "Classifier Glyphs" view. This view should allow to remove or change the class to which each glyph is assigned. Gamera has already this functionality as part of its interactive classifier:

![screen shot 2017-06-16 at 5 52 23 pm](https://user-images.githubusercontent.com/492229/27245991-9ec149a4-52bc-11e7-82c7-79bd7dd98811.png)

**Comment by pf-physics** [comment]
Commits 770bedf 6d3fbe3 b041585 c8bf2d7
